// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shkomdvsfitmynacprbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoa29tZHZzZml0bXluYWNwcmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzgxOTIsImV4cCI6MjA3MjA1NDE5Mn0.-qUHNBo6KqDjeI5Kb8Yy-bZ-jPcaPJDJVl8pxqsG-jI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});